import glob
import re

mapping = {
    '2—4h': '2–4h',
    '39—C': '39°C',
    '40—C': '40°C',
    '6004245—hl=de': '6004245?hl=de',
    'gaoptout—hl=de': 'gaoptout=de',
    'Atmosph—re': 'Atmosphäre',
    'Augenh—he': 'Augenhöhe',
    'Ausfl—ge': 'Ausflüge',
    'Ausfl—gen': 'Ausflügen',
    'Baumhausd—rfer': 'Baumhausdörfer',
    'Bergd—rfer': 'Bergdörfer',
    'Blasfont—nen': 'Blasfontänen',
    'Blutk—rperchen': 'Blutkörperchen',
    'Bl—tter': 'Blätter',
    'Campn—chte': 'Campnächte',
    'DATENSCHUTZERKL—RUNG': 'DATENSCHUTZERKLÄRUNG',
    'Datenschutzerkl—rung': 'Datenschutzerklärung',
    'Direktfl—ge': 'Direktflüge',
    'Dorfabl—ufen': 'Dorfabläufen',
    'Drau—en': 'Draußen',
    'Ersch—pfung': 'Erschöpfung',
    'Erz—hl': 'Erzähl',
    'Fischerh—tten': 'Fischerhütten',
    'Fischschw—rme': 'Fischschwärme',
    'Fischschw—rmen': 'Fischschwärmen',
    'Flederm—use': 'Fledermäuse',
    'Fl—ssigkeit': 'Flüssigkeit',
    'Font—nen': 'Fontänen',
    'Fu—ball': 'Fußball',
    'F—hrtickets': 'Fährtickets',
    'Gef—hl': 'Gefühl',
    'Gel—nde': 'Gelände',
    'Ger—che': 'Gerüche',
    'Gespr—che': 'Gespräche',
    'Gespr—chen': 'Gesprächen',
    'Getr—nk': 'Getränk',
    'Großz—gigkeit': 'Großzügigkeit',
    'Gr—nde': 'Gründe',
    'Gr—ndung': 'Gründung',
    'Gästeh—user': 'Gästehäuser',
    'H—gel': 'Hügel',
    'H—hle': 'Höhle',
    'Identit—t': 'Identität',
    'Kalksteinw—nde': 'Kalksteinwände',
    'Klippenspr—nge': 'Klippensprünge',
    'Kostengr—nden': 'Kostengründen',
    'K—rper': 'Körper',
    'K—rperlich': 'Körperlich',
    'K—mmern': 'Kümmern',
    'K—rzer': 'Kürzer',
    'K—rzeren': 'Kürzeren',
    'K—nstlich': 'Künstlich',
    'Lebensrealit—ten': 'Lebensrealitäten',
    'L—cken': 'Lücken',
    'L—nge': 'Länge',
    'Mai—Okt': 'Mai–Okt',
    'Mangrovenw—lder': 'Mangrovenwälder',
    'Meeress—uger': 'Meeressäuger',
    'Milit—r': 'Militär',
    'M—cken': 'Mücken',
    'M—ckenschutz': 'Mückenschutz',
    'M—ckenspiralen': 'Mückenspiralen',
    'M—sse': 'müsse',
    'Naturph—nomene': 'Naturphänomene',
    'Oberfl—che': 'Oberfläche',
    'Parkgeb—hren': 'Parkgebühren',
    'Pers—nliche': 'Persönliche',
    'Plan—nderungen': 'Planänderungen',
    'Pl—tzlich': 'Plötzlich',
    'Preisrealit—t': 'Preisrealität',
    'Pr—vention': 'Prävention',
    'P—sse': 'Pässe',
    'Reisepl—ne': 'Reisepläne',
    'Rückfl—ge': 'Rückflüge',
    'Schlafpl—tzen': 'Schlafplätzen',
    'Schw—che': 'Schwäche',
    'Sch—ttelfrost': 'Schüttelfrost',
    'Spr—nge': 'Sprünge',
    'Str—nde': 'Strände',
    'St—dten': 'Städten',
    'St—hlen': 'Stühlen',
    'St—mmen': 'Stämmen',
    'St—tzpunkt': 'Stützpunkt',
    'Tauchertr—ume': 'Taucherträume',
    'Tauchg—nge': 'Tauchgänge',
    'T—rkisblaues': 'Türkisblaues',
    'Unregelm—ige': 'Unregelmäßige',
    'Visageb—hren': 'Visagebühren',
    'Vorf—hrungen': 'Vorführungen',
    'Walf—ngerdorf': 'Walfängerdorf',
    'Walsch—del': 'Walschädel',
    'Wasserst—nde': 'Wasserstände',
    'Wasserst—nden': 'Wasserständen',
    'Wei—spitzen': 'Weißspitzen',
    'W—hrend': 'Während',
    'W—hrenddessen': 'Währenddessen',
    'W—hrung': 'Währung',
    'W—nde': 'Wände',
    'W—nden': 'Wänden',
    'W—sche': 'Wäsche',
    'Zahlungsabl—ufe': 'Zahlungsabläufe',
    'Zun—chst': 'Zunächst',
    'Zus—tzliches': 'Zusätzliches',
    'Zwillingsbr—dern': 'Zwillingsbrüdern',
    'Z—hnen': 'Zähnen',
    'aufgebl—ht': 'aufgebläht',
    'ausw—hlt': 'auswählt',
    'au—en': 'außen',
    'ber—hmt': 'berühmt',
    'd—nn': 'dünn',
    'erh—ht': 'erhöht',
    'er—ffnen': 'eröffnen',
    'farbenpr—chtigen': 'farbenprächtigen',
    'f—hren': 'führen',
    'f—hrst': 'führst',
    'f—hrt': 'führt',
    'f—nf': 'fünf',
    'ganzj—hrig': 'ganzjährig',
    'gef—hrt': 'geführt',
    'geh—ren': 'gehören',
    'geh—rt': 'gehört',
    'geh—rten': 'gehörten',
    'gepr—gt': 'geprägt',
    'gesch—tzt': 'geschützt',
    'get—tet': 'getötet',
    'gr—ere': 'größere',
    'kn—pften': 'knüpften',
    'hinzugef—gt': 'hinzugefügt',
    'h—ufig': 'häufig',
    't—glichen': 'täglichen',
    't—glicher': 'täglicher',
    'kn—pft': 'knüpft',
    'unz—hlige': 'unzählig',
    'l—ngst': 'längst',
    'sch—n': 'schön',
    'sch—ner': 'schöner',
    't—rkisblaues': 'türkisblaues',
    'wundersch—n': 'wunderschön',
    'gesto—en': 'gestoßen',
    'h—tten': 'hätten',
    'h—tte': 'hätte',
    'n—hrstoffreich': 'nährstoffreich',
    'ungef—hr': 'ungefähr',
    'vern—nftig': 'vernünftig',
    'v—llig': 'völlig',
    'zweit—gige': 'zweitägige',
    'st—rkster': 'stärkster',
    'untersch—tzt': 'unterschätzt',
    'spektakul—r': 'spektakulär',
    'g—ngige': 'gängige',
    'zuverl—ssigste': 'zuverlässigste',
    'regelm—ig': 'regelmäßig',
    'j—hrliche': 'jährliche',
    'l—ngste': 'längste',
    'm—hsam': 'mühsam',
    'sch—tzen': 'schützen',
    'sch—tzt': 'schützt',
    '—ige': 'äßige',
    'au—erplanm—ige': 'außerplanmäßige',
}
pattern = re.compile(r'\b(\w*—\w*)\b')
files = glob.glob('de/**/*.html', recursive=True)
for path in files:
    with open(path, 'r', encoding='utf-8', errors='replace') as f:
        text = f.read()
    original = text
    for old, new in mapping.items():
        text = text.replace(old, new)
    if text != original:
        with open(path, 'w', encoding='utf-8') as f:
            f.write(text)
remaining = []
for path in files:
    text = open(path, 'r', encoding='utf-8', errors='replace').read()
    for m in pattern.findall(text):
        remaining.append((path, m))
print('remaining', len(remaining))
for path, token in remaining:
    print(path, token)
PY