import glob
from pathlib import Path

mapping = {
    '2—4h': '2–4h',
    '39—C': '39°C',
    '40—C': '40°C',
    '6004245—hl=de': '6004245?hl=de',
    'gaoptout—hl=de': 'gaoptout?hl=de',
    'Atmosph—re': 'Atmosphäre',
    'Augenh—he': 'Augenhöhe',
    'Ausfl—ge': 'Ausflüge',
    'Ausfl—gen': 'Ausflügen',
    'Baumhausd—rfer': 'Baumhausdörfer',
    'Bergd—rfer': 'Bergdörfer',
    'Blasfont—nen': 'Blasfontänen',
    'Blutk—rperchen': 'Blutkörperchen',
    'Bl—tter': 'Blätter',
    'Campn—chte': 'Campnächte',
    'DATENSCHUTZERKL—RUNG': 'DATENSCHUTZERKLÄRUNG',
    'Datenschutzerkl—rung': 'Datenschutzerklärung',
    'Direktfl—ge': 'Direktflüge',
    'Dorfabl—ufen': 'Dorfabläufen',
    'Drau—en': 'Draußen',
    'Ersch—pfung': 'Erschöpfung',
    'Erz—hl': 'Erzähl',
    'Erz—hlt': 'Erzählt',
    'Erz—hlten': 'Erzählten',
    'Fischerh—tten': 'Fischerhütten',
    'Fischschw—rme': 'Fischschwärme',
    'Fischschw—rmen': 'Fischschwärmen',
    'Flederm—use': 'Fledermäuse',
    'Fl—ssigkeit': 'Flüssigkeit',
    'Font—nen': 'Fontänen',
    'Fu—ball': 'Fußball',
    'F—hrtickets': 'Fährtickets',
    'Gef—hl': 'Gefühl',
    'Gel—nde': 'Gelände',
    'Ger—che': 'Gerüche',
    'Gespr—che': 'Gespräche',
    'Gespr—chen': 'Gesprächen',
    'Getr—nk': 'Getränk',
    'Großz—gigkeit': 'Großzügigkeit',
    'Gr—nde': 'Gründe',
    'Gr—ndung': 'Gründung',
    'Gästeh—user': 'Gästehäuser',
    'H—gel': 'Hügel',
    'H—hle': 'Höhle',
    'Identit—t': 'Identität',
    'Kalksteinw—nde': 'Kalksteinwände',
    'Klippenspr—nge': 'Klippensprünge',
    'Kostengr—nden': 'Kostengründen',
    'K—rper': 'Körper',
    'K—rperlich': 'Körperlich',
    'K—mmern': 'Kümmern',
    'K—rzer': 'Kürzer',
    'K—rzeren': 'Kürzeren',
    'K—nstlich': 'Künstlich',
    'Lebensrealit—ten': 'Lebensrealitäten',
    'L—cken': 'Lücken',
    'L—nge': 'Länge',
    'Mai—Okt': 'Mai–Okt',
    'Mangrovenw—lder': 'Mangrovenwälder',
    'Meeresschildkr—ten': 'Meeresschildkröten',
    'Meeress—uger': 'Meeressäuger',
    'Milit—r': 'Militär',
    'M—cken': 'Mücken',
    'M—ckenschutz': 'Mückenschutz',
    'M—ckenspiralen': 'Mückenspiralen',
    'M—sse': 'müsse',
    'Naturph—nomene': 'Naturphänomene',
    'Oberfl—che': 'Oberfläche',
    'Parkgeb—hren': 'Parkgebühren',
    'Pers—nliche': 'Persönliche',
    'Plan—nderungen': 'Planänderungen',
    'Pl—tzlich': 'Plötzlich',
    'Preisrealit—t': 'Preisrealität',
    'Pr—vention': 'Prävention',
    'P—sse': 'Pässe',
    'Reisepl—ne': 'Reisepläne',
    'Rückfl—ge': 'Rückflüge',
    'Schlafpl—tzen': 'Schlafplätzen',
    'Schw—che': 'Schwäche',
    'Sch—ttelfrost': 'Schüttelfrost',
    'Spr—nge': 'Sprünge',
    'Str—nde': 'Strände',
    'St—dten': 'Städten',
    'St—hlen': 'Stühlen',
    'St—mmen': 'Stämmen',
    'St—tzpunkt': 'Stützpunkt',
    'Tauchertr—ume': 'Taucherträume',
    'Tauchg—nge': 'Tauchgänge',
    'T—rkisblaues': 'Türkisblaues',
    'Ungef—hrer': 'Ungefährer',
    'Unregelm—ige': 'Unregelmäßige',
    'Visageb—hren': 'Visagebühren',
    'Vorf—hrungen': 'Vorführungen',
    'Walf—ngerdorf': 'Walfängerdorf',
    'Walsch—del': 'Walschädel',
    'walsch—del': 'walschädel',
    'Walsch—del': 'Walschädel',
    'wei—t': 'weißt',
    'Wasserst—nde': 'Wasserstände',
    'Wasserst—nden': 'Wasserständen',
    'Wei—spitzen': 'Weißspitzen',
    'W—hrend': 'Während',
    'W—hrenddessen': 'Währenddessen',
    'W—hrung': 'Währung',
    'W—nde': 'Wände',
    'W—nden': 'Wänden',
    'W—sche': 'Wäsche',
    'Zahlungsabl—ufe': 'Zahlungsabläufe',
    'Zun—chst': 'Zunächst',
    'Zus—tzliches': 'Zusätzliches',
    'Zwillingsbr—dern': 'Zwillingsbrüdern',
    'Z—hnen': 'Zähnen',
    'aufgebl—ht': 'aufgebläht',
    'ausw—hlt': 'auswählt',
    'au—en': 'außen',
    'au—erplanm—ige': 'außerplanmäßige',
    'ber—hmt': 'berühmt',
    'd—nn': 'dünn',
    'erh—ht': 'erhöht',
    'erz—hlen': 'erzählen',
    'erz—hlt': 'erzählte',
    'erz—hlte': 'erzählte',
    'erz—hlten': 'erzählten',
    'er—ffnen': 'eröffnen',
    'farbenpr—chtigen': 'farbenprächtigen',
    'f—hren': 'führen',
    'f—hrst': 'führst',
    'f—hrt': 'führt',
    'f—nf': 'fünf',
    'ganzj—hrig': 'ganzjährig',
    'gef—hrt': 'geführt',
    'geh—ren': 'gehören',
    'geh—rt': 'gehört',
    'geh—rten': 'gehörten',
    'gepr—gt': 'geprägt',
    'gesch—tzt': 'geschützt',
    'gesto—en': 'gestoßen',
    'get—tet': 'getötet',
    'gr—ere': 'größere',
    'g—ngige': 'gängige',
    'haupts—chlich': 'hauptsächlich',
    'hinzugef—gt': 'hinzugefügt',
    'h—bscher': 'hübscher',
    'h—ngen': 'hängen',
    'h—rten': 'hörten',
    'h—rteste': 'härteste',
    'h—tte': 'hätte',
    'h—tten': 'hätten',
    'h—ufig': 'häufig',
    'h—ufiger': 'häufiger',
    'irref—hrendes': 'irreführendes',
    'j—hrliche': 'jährliche',
    'kn—pft': 'knüpft',
    'kn—pften': 'knüpften',
    'kr—nender': 'krönender',
    'k—mmern': 'kümmern',
    'k—nstlich': 'künstlich',
    'k—rzer': 'kürzer',
    'k—rzeren': 'kürzeren',
    'l—ngst': 'längst',
    'l—ngste': 'längste',
    'm—hsam': 'mühsam',
    'm—sse': 'müsse',
    'n—hrstoffreich': 'nährstoffreich',
    'regelm—ig': 'regelmäßig',
    'sch—n': 'schön',
    'sch—ner': 'schöner',
    'sch—tzen': 'schützen',
    'sch—tzt': 'schützt',
    'spektakul—r': 'spektakulär',
    'spektakul—re': 'spektakuläre',
    'st—rkster': 'stärkster',
    't—gliche': 'tägliche',
    't—glichen': 'täglichen',
    't—glicher': 'täglicher',
    't—rkisblaues': 'türkisblaues',
    'ungef—hr': 'ungefähr',
    'ungew—hnlich': 'ungewöhnlich',
    'unregelm—ig': 'unregelmäßig',
    'untersch—tzt': 'unterschätzt',
    'unz—hlige': 'unzählige',
    'vern—nftig': 'vernünftig',
    'verspätungsanf—llig': 'verspätungsanfällig',
    'v—llig': 'völlig',
    'weltber—hmte': 'weltberühmte',
    'weltber—hmten': 'weltberühmten',
    'wundersch—n': 'wunderschön',
    'zusammengew—rfelten': 'zusammengewürfelten',
    'zus—tzliche': 'zusätzliche',
    'zus—tzlichen': 'zusätzlichen',
    'zuverl—ssigste': 'zuverlässigste',
    'zweit—gige': 'zweitägige',
    'z—hlen': 'zählen',
}

files = sorted(Path('de').glob('**/*.html'))
changed = []
for path in files:
    text = path.read_text(encoding='utf-8', errors='replace')
    original = text
    for bad, good in mapping.items():
        text = text.replace(bad, good)
    if text != original:
        path.write_text(text, encoding='utf-8')
        changed.append(str(path))

print('changed files:', len(changed))
for path in changed:
    print(path)

# verify remaining broken word-like tokens
import re
pattern = re.compile(r'\b[\wÄÖÜäöüß]*—[\wÄÖÜäöüß]*\b')
remaining = {}
for path in files:
    text = path.read_text(encoding='utf-8', errors='replace')
    for token in pattern.findall(text):
        if token not in mapping:
            remaining.setdefault(token, []).append(str(path))
print('remaining unique tokens:', len(remaining))
for token, paths in sorted(remaining.items()):
    print(token, '->', ', '.join(paths))
